### ISSUE TITLE
Check players in a group of worlds?

### ISSUE THREAD

**Issue by CrazyMMG** [thienbao860/World-Expansion#2]
Is there a way to check for players in a group of worlds not just one? If not, could you please add this feature!

**Comment by thienbao860** [comment]
Hello. If you were referring about group from Vault plugin, you can use this placeholder: \%world\_players\_\<world\<\_\<groupName\>\%

**Comment by CrazyMMG** [comment]
No, I mean as in a group of worlds specified the the placeholder. Example: %world_players_world1+world2%

So the output would be the players in world1 and the players in world2, added together.

**Comment by thienbao860** [comment]
Oh I see. Maybe I will add it later, thanks for suggestion
